server:
  port: 5000
spring:
  profiles:
    active: @spring.profiles.active@
---
var: dev
spring:
  config:
    activate:
      on-profile: dev
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 5cf7941e4240f37e22a5
            clientSecret: 524608c256e1c3ed6e80747cafb4bf08af4e3793
            scope:
              - user:email
              - read:user
        provider:
          github:
            user-name-attribute: login
---
var: prod
spring:
  config:
    activate:
      on-profile: prod
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 7b93bdbd65644f9f4ab5
            clientSecret: e5217cf533e8a1b0e4fc541971beae70be849313
            scope:
              - user:email
              - read:user
        provider:
          github:
            user-name-attribute: login
---